# Generated by Django 5.0 on 2023-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
